config/routes.rb
Rails.application.routes.draw do
  get 'friends/index'

  get 'friends/destroy'

  resources :friend_requests
  get 'sessions/new'

  resources :subjects
  resources :instructors
  resources :courses
  resources :users
  root 'login#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/results', to: 'courses#results'
  post '/enrollments/create', to: 'courses#create_enrollment'
  delete 'enrollments/delete', to: 'courses#destroy_enrollment'
  delete 'enrollments/deletereg', to: 'courses#destroy_enrollment_reg'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_many :enrollments
	has_many :courses, :through => :enrollments
	has_many :friend_requests, dependent: :destroy
	has_many :pending_friends, :through => :friend_requests, :source => :friend
	has_many :friendships, dependent: :destroy
  	has_many :friends, through: :friendships

	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
	                    format: { with: VALID_EMAIL_REGEX },
	                    uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

  	def remove_friend(friend)
    	current_user.friends.destroy(friend)
  	end

	def User.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :users_only, only: [:show]

  def show
    @user = User.find(params[:id])
    @enrolled_courses = @user.courses
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/views/users/_user_enrollments.html.erb
<% if @enrolled_courses.empty? %>
      
  <p>You are not enrolled in any courses!</p>

<% else %>
  
  <table class="table table-striped">
    <thead class="thead-inverse">
      <tr>
        <th>Name</th>
        <th>Code</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @enrolled_courses.each do |course| %>
        <tr>
          <td><%= course.name %></td>
          <td><%= course.code %></td>
          <td><%= course.description %></td>
          <td><%= button_to 'Show', course, class: 'btn .btn-success darkGrayButton' %></td>
          <td><%= button_to 'Unenroll', enrollments_delete_path, {method: :delete, remote: true, params:{course_id: course, user_id: current_user}, class: 'btn .btn-success rbutton'} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Sign up</h1>
    <br>
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class ="col-sm-1">
  </div>
  <aside class="col-md-10">
    <h1><%= @user.name %></h1>
    <p><%= @user.email %></p>
    <br>
    <h3>Enrolled Courses</h3>

    <div id="user_enrollments">
      <% if @enrolled_courses.empty? %>
      
        <p>You are not enrolled in any courses!</p>

      <% else %>
        <% if @user == current_user %>
          <table class="table table-striped">
            <thead class="thead-inverse">
              <tr>
                <th>Name</th>
                <th>Code</th>
                <th>Description</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @enrolled_courses.each do |course| %>
                <tr>
                  <td><%= course.name %></td>
                  <td><%= course.code %></td>
                  <td><%= course.description %></td>
                  <td><%= button_to 'Info', course, method: :get, class: 'btn .btn-success darkGrayButton' %></td>
                  <td><%= button_to 'Unenroll', enrollments_delete_path, {method: :delete, remote: true, params:{course_id: course, user_id: current_user}, class: 'btn .btn-success rbutton'} %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <table class="table table-striped">
            <thead class="thead-inverse">
              <tr>
                <th>Name</th>
                <th>Code</th>
                <th>Description</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @enrolled_courses.each do |course| %>
                <tr>
                  <td><%= course.name %></td>
                  <td><%= course.code %></td>
                  <td><%= course.description %></td>
                  <td><%= button_to 'Info', course, method: :get, class: 'btn .btn-success darkGrayButton' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      
      <% end %>
    </div>
  
  </aside>
  <div class ="col-sm-1">
  </div>
</div>