config/routes.rb
Rails.application.routes.draw do
  get 'friends/index'

  get 'friends/destroy'

  resources :friend_requests
  get 'sessions/new'

  resources :subjects
  resources :instructors
  resources :courses
  resources :users
  root 'login#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/results', to: 'courses#results'
  post '/enrollments/create', to: 'courses#create_enrollment'
  delete 'enrollments/delete', to: 'courses#destroy_enrollment'
  delete 'enrollments/deletereg', to: 'courses#destroy_enrollment_reg'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :users_only

  # GET /courses
  # GET /courses.json
  def index
    #get courses to show, subjects for search params
    @courses = Course.all
    @subjects = Subject.all.order(:name)

    #get user and courses to whether to display enroll/unenroll
    @user = current_user
    @enrolled_courses = @user.courses
  end

  def results
    #get courses to show, subjects for search params
    @courses = Course.search(params)
    @subjects = Subject.all.order(:name)

    #get user and courses to whether to display enroll/unenroll
    @user = current_user
    @enrolled_courses = @user.courses

    respond_to do |format|
      format.js
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @users = Course.find(@course.id).users
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /enrollment
  def create_enrollment
    @current_user = current_user
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @current_user}
      else
        format.html { redirect_to :index }
      end
    end
  end

  #DELETE /enrollments/1
  def destroy_enrollment
    @enrollment = Enrollment.find_by(course_id: params[:course_id],user_id: params[:user_id])
    @enrollment.destroy

    @user = User.find(params[:user_id])
    @enrolled_courses = @user.courses

    respond_to do |format|
      format.js
    end
  end

  #DELETE /enrollments/1
  def destroy_enrollment_reg
    @enrollment = Enrollment.find_by(course_id: params[:course_id],user_id: params[:user_id])
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to @current_user}
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :code, :description)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:course_id, :user_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :course_name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :course_code %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :course_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/_result.html.erb
<div class = "row">
    <h3> <%= @courses.length %> matches found </h3>
</div>
<br>
<br>
<div class = "row">
	<table class="table table-striped">
	    <thead class="thead-inverse">
	      <tr>
	        <th>Name</th>
	        <th>Code</th>
	        <th>Description</th>
	        <th colspan="3"></th>
	        <th colspan="3"></th>
	      </tr>
	    </thead>

	    <tbody>
	      <% @courses.each do |course| %>
	        <tr>
	          <td><%= course.name %></td>
	          <td><%= course.code %></td>
	          <td><%= course.description %></td>
	          <td><%= button_to 'Info', course, method: :get, class: 'btn .btn-success darkGrayButton'%></td>
	          <% if @enrolled_courses.include?(course)%>
	          	<td><%= button_to 'Unenroll', enrollments_deletereg_path, {method: :delete, params:{course_id: course, user_id: current_user}, class: 'btn .btn-success rbutton'} %></td>
	          <% else %>
	          	<td><%= button_to 'Enroll', enrollments_create_path, params:{enrollment: {course_id: course, user_id: current_user}}, class: 'btn .btn-success gbutton' %></td>
	          <% end %>
	        </tr>
	      <% end %>
	    </tbody>
	</table>
</div>

app/views/courses/_search_results.html.erb
<div class = "container">
	<%if @courses.nil? || @courses.length == 0%>
		<br>
		<h2>No Matches Found</h2>
	<% else %>
		<%= render "result" %>
	<% end %>
</div>

app/views/courses/_user_enrollments.html.erb
<% if @enrolled_courses.empty? %>
      
  <p>You are not enrolled in any courses!</p>

<% else %>
  
  <table class="table table-striped">
    <thead class="thead-inverse">
      <tr>
        <th>Name</th>
        <th>Code</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @enrolled_courses.each do |course| %>
        <tr>
          <td><%= course.name %></td>
          <td><%= course.code %></td>
          <td><%= course.description %></td>
          <td><%= link_to 'Show', course, method: :get, class: 'btn .btn-success darkGrayButton' %></td>
          <td><%= button_to 'Unenroll', enrollments_delete_path, {method: :delete, remote: true, params:{course_id: course, user_id: current_user}, class: 'btn .btn-success rbutton'} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

app/views/courses/destroy_enrollment.js.erb
$('#user_enrollments').html("<%= escape_javascript (render(partial: 'user_enrollments')) %>");

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>
<script>
  function submitFrmAjax(){
   $.ajax({
         url : "/results",
         data : $("form#result_form").serialize()
    });
  }
</script>

<div class="col-md-1">
</div>

<div class="col-md-10">
  <h1>Courses</h1>
  <p>Here you can find all the courses taught at Brandeis.</p>

  <br>
  <div class="row">
    <%= form_tag results_path, method: 'get', remote: true, role: "form",class: "form", id: "result_form" do %>
      <div class="col-md-5"><%= text_field_tag(:keywords, params[:keywords], class: 'form-control', :placeholder => "Enter Keywords Here", onkeyup: 'submitFrmAjax()') %></div>
      <div class="col-md-5"><%= select_tag(:subject, options_from_collection_for_select(@subjects, "id", "name"), prompt: "Select a Subject", class: 'form-control', onchange: 'submitFrmAjax()') %></div>
    <% end %>
  </div>
  <br>

  <div id="search_results">
  </div>
</div>

<div class="col-md-1">
</div>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/results.js.erb
$('#search_results').html("<%= escape_javascript (render(partial: 'search_results')) %>");

app/views/courses/show.html.erb
<div class ="col-sm-1">
</div>

<div class="col-md-10">
	<p id="notice"><%= notice %></p>

	<h2>
	  <strong><%= @course.name %></strong>
	</h2>

	<h6>
	  <strong>Code:</strong>
	  <%= @course.code %>
	</h6>

	<h6>
	  <strong>Description:</strong>
	  <%= @course.description %>
	</h6>

	<br>
	<h4>Enrolled Users:</h4>
	<div class = "row">
		<table class="table table-striped">
		    <thead class="thead-inverse">
		      <tr>
		        <th>Name</th>
		        <th style="width: 10%"></th>
		      </tr>
		    </thead>

		    <tbody>
		      <% @users.each do |user| %>
		        <tr>
		          <td><strong><%= user.name %></strong></td>
		          <td><%= button_to 'Profile', user, method: :get, class: 'btn .btn-success darkGrayButton' %></td>
		        </tr>
		      <% end %>
		    </tbody>
		</table>
	</div>
</div>

<div class ="col-sm-1">
</div>