config/routes.rb
Rails.application.routes.draw do
  get 'friends/index'

  get 'friends/destroy'

  resources :friend_requests
  get 'sessions/new'

  resources :subjects
  resources :instructors
  resources :courses
  resources :users
  root 'login#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/results', to: 'courses#results'
  post '/enrollments/create', to: 'courses#create_enrollment'
  delete 'enrollments/delete', to: 'courses#destroy_enrollment'
  delete 'enrollments/deletereg', to: 'courses#destroy_enrollment_reg'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <% if logged_in? %>
                <a class="navbar-brand parent" href="/">
                  <img alt="Brand" src="https://avatars1.githubusercontent.com/u/10900222?s=460&v=4" class="scaled-image">
                </a>
              <% else %>
                <a class="navbar-brand parent" href="/">
                  <img alt="Brand" src="https://avatars1.githubusercontent.com/u/10900222?s=460&v=4" class="scaled-image">
                </a>
              <% end %>
            </li>
            <% if logged_in? %>
              <li><%= link_to "Home", current_user %></li>
            <% else %>
              <li><%= link_to "Home", root_path %></li>
            <% end %>
            <li><%= link_to "Courses", courses_path %></li>
            <li><%= link_to "Instructors", instructors_path %></li>
            <li><%= link_to "Subjects", subjects_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <%= button_to "Log Out", {:controller => :sessions, :action => 'destroy', :id => session[:user_id]}, :method => :delete, :class => "btn btn-primary white-text" %>
            <% else %>
              <a type="button" class="btn btn-primary white-text" href="/login">Log In</a>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%= yield %>
  </body>
</html>